#ifndef _SYSLINK_ECODE_H
#define _SYSLINK_ECODE_H

/*正值表示警告错误,也是以100为基数,某些情况可以忽略可以忽略*/

/*保留的syslink原错误代码*/
/*syslink*/
#define ESYSLINK_B_MEMORY					Ipc_E_MEMORY 
#define ESYSLINK_B_BUSY						Ipc_S_BUSY
#define ESYSLINK_B_NOTREADY					Ipc_E_NOTREADY
#define ESYSLINK_B_FAIL						Ipc_E_FAIL
#define ESYSLINK_B_ALREADYSETUP				Ipc_S_ALREADYSETUP
/*notify*/
#define ENOTIFIER_B_ALREADYEXISTS			Notify_E_ALREADYEXISTS
#define ENOTIFIER_B_FAIL					Notify_E_FAIL
#define ENOTIFIER_B_EVTNOTREGISTERED		Notify_E_EVTNOTREGISTERED
#define ENOTIFIER_B_NOTINITIALIZED			Notify_E_NOTINITIALIZED
#define ENOTIFIER_B_EVTDISABLED				Notify_E_EVTDISABLED
#define ENOTIFIER_B_TIMEOUT					Notify_E_TIMEOUT

/*messageq*/
#define	EMESSAGEQ_B_TIMEOUT					MessageQ_E_TIMEOUT
#define	EMESSAGEQ_B_UNBLOCKED				MessageQ_E_UNBLOCKED
#define	EMESSAGEQ_B_FAIL					MessageQ_E_FAIL
#define EMESSAGEQ_B_NOTFOUND                MessageQ_E_NOTFOUND 

/*heap bufmp/memmp*/
#define EMESSAGEQ_B_HEAP_FAIL					HeapBufMP_E_FAIL
#define EMESSAGEQ_B_HEAP_NOTFOUND				HeapBufMP_E_NOTFOUND

/*ringio*/
#define	ERPE_B_NOTFOUND						RingIO_E_NOTFOUND
#define	ERPE_B_INVALIDSTATE					RingIO_E_INVALIDSTATE
#define	ERPE_B_VARIABLEATTRIBUTE			RingIO_E_VARIABLEATTRIBUTE
#define	ERPE_B_PENDINGDATA					RingIO_E_PENDINGDATA
#define	ERPE_B_WRONGSTATE					RingIO_E_WRONGSTATE
#define	RPE_BS_PENDINGATTRIBUTE				RingIO_S_PENDINGATTRIBUTE
#define	ERPE_B_PENDINGATTRIBUTE				RingIO_E_PENDINGATTRIBUTE
#define	ERPE_B_BUFFULL						RingIO_E_BUFFULL
#define	ERPE_B_BUFWRAP						RingIO_E_BUFWRAP
#define	RPE_BS_NOTCONTIGUOUSDATA			RingIO_S_NOTCONTIGUOUSDATA
#define	ERPE_B_BUFEMPTY						RingIO_E_BUFEMPTY
#define	ERPE_B_FAIL							RingIO_E_FAIL
#define	ERPE_B_INVALIDARG					RingIO_E_INVALIDARG
#define	ERPE_B_NOTIFYFAIL					RingIO_E_NOTIFYFAIL
#define ERPE_B_INVALIDCONTEXT				RingIO_E_INVALIDCONTEXT

/*--------------------------------------------------------------------*/
/*自定义错误代码*/

#define ECODE_BASE							  100
#define SUCCESS								  0

#define EFAIL								-(ECODE_BASE + 1)
#define INVALID								-(ECODE_BASE + 2)
#define EMEMORY								-(ECODE_BASE + 3)
#define EOBJNAME							-(ECODE_BASE + 4)
#define EOBJTYPE							-(ECODE_BASE + 5)
#define EOBJISBUSY							-(ECODE_BASE + 6)
#define EOBJINVALID							-(ECODE_BASE + 7)
#define EPARMINVALID                        -(ECODE_BASE + 43)
#define EPARENTINVALID                      -(ECODE_BASE + 44)
/*syslink*/
#define ESYSLINK_MEMORY						  EMEMORY
#define ESYSLINK_OBJNAME					  EOBJNAME
#define ESYSLINK_EXISTAREADY				-(ECODE_BASE + 8)
#define ESYSLINK_ROLE						-(ECODE_BASE + 9)
#define ESYSLINK_NOSYSLINK					-(ECODE_BASE + 10)
#define ESYSLINK_BUSY						-(ECODE_BASE + 11)
/*notifier*/
#define NOTIFIER_OBJNAME					  EOBJNAME
#define ENOTIFIER_FAIL						  EFAIL
#define ENOTIFIER_MEMORY					  EMEMORY
#define ENOTIFIER_INVALID					  INVALID
#define ENOTIFIER_EVQUESTAT					-(ECODE_BASE + 14)
#define ENOTIFIER_EVQOVERFLOW				-(ECODE_BASE + 15)
#define ENOTIFIER_NOTUNREGISTERED			-(ECODE_BASE + 16)
#define ENOTIFIER_REOPEN					-(ECODE_BASE + 17)
#define ENOTIFIER_QUEUE						-(ECODE_BASE + 18)
#define ENOTIFIER_NOTUNREGISTER				-(ECODE_BASE + 19)
#define ENOTIFIER_OPEN						-(ECODE_BASE + 20)
#define ENOTIFIER_MODE						-(ECODE_BASE + 21)
#define ENOTIFIER_CALLBACK					-(ECODE_BASE + 22)
#define ENOTIFIER_NOTREGISTERED				-(ECODE_BASE + 23)
#define ENOTIFIER_INTRRUPT					-(ECODE_BASE + 53)
//#define ENOTIFIER_INVALID					-(ECODE_BASE + 54)
#define ENOTIFIER_TIMEOUT					-(ECODE_BASE + 55)
#define ENOTIFIER_AGAIN						-(ECODE_BASE + 56)
#define ENOTIFIER_RECONSTRUCT				-(ECODE_BASE + 57)
/*messageq*/
#define	EMESSAGEQ_OBJNAME					  EOBJNAME
#define	EMESSAGEQ_MEMORY					  EMEMORY
#define	EMESSAGEQ_INVALID					  INVALID
#define	EMESSAGEQ_FAIL						  EFAIL
#define	EMESSAGEQ_RECONSTRUCT				-(ECODE_BASE + 24)
#define	EMESSAGEQ_HEAPCREATE				-(ECODE_BASE + 25)
#define	EMESSAGEQ_HIDEXIST					-(ECODE_BASE + 26)
#define	EMESSAGEQ_SREGION					-(ECODE_BASE + 27)
#define	EMESSAGEQ_BUFTYPE					-(ECODE_BASE + 28)
#define	EMESSAGEQ_INVALIDPAR				-(ECODE_BASE + 29)
#define	EMESSAGEQ_REINIT					-(ECODE_BASE + 30)
#define	EMESSAGEQ_RBOXNOTCLOSED				-(ECODE_BASE + 31)
#define	EMESSAGEQ_NOTIFYNOTCLOSED			-(ECODE_BASE + 32)
#define	EMESSAGEQ_MSGBOXEXIST				-(ECODE_BASE + 33)
#define	EMESSAGEQ_REATTACHED				-(ECODE_BASE + 34)
#define	EMESSAGEQ_OUTOFRBOX					-(ECODE_BASE + 35)
#define	EMESSAGEQ_EVTLEVEL					-(ECODE_BASE + 36)
#define	EMESSAGEQ_INVALIDBOXID				-(ECODE_BASE + 37)
#define EMESSAGEQ_CALLBACK                  -(ECODE_BASE + 38)
#define EMESSAGEQ_PROCID                    -(ECODE_BASE + 39)
#define EMESSAGEQ_INVALIDMSGBOX             -(ECODE_BASE + 45)
#define EMESSAGEQ_INVALIDEVTLVL				-(ECODE_BASE + 46)
#define EMESSAGEQ_INVALIDHEAPID				-(ECODE_BASE + 58)
#define EMESSAGEQ_HEAPOPEN					-(ECODE_BASE + 59)

/*ringpipe*/
#define ERPE_FAIL							  EFAIL
#define ERPE_INVALID 						  INVALID
#define ERPE_MEMEROY						  EMEMORY
#define ERPE_OBJNAME 						  EOBJNAME
#define EPRE_EXISTNOTIFY 					-(ECODE_BASE + 40)
#define ERPE_SPACE_TYPE 					-(ECODE_BASE + 41)
#define ERPE_REOPEN 						-(ECODE_BASE + 42)
#define ERPE_BUFEXIST						-(ECODE_BASE + 47)
#define ERPE_INVALIDPARM					-(ECODE_BASE + 48)
#define ERPE_IOBUFHANDLE					-(ECODE_BASE + 49)
#define ERPE_NOTIFYEXIST					-(ECODE_BASE + 50)
#define ERPE_OPEN							-(ECODE_BASE + 51)
#define ERPE_INVALIDPARAM					-(ECODE_BASE + 52)
	
#endif
